[tool.poetry]
name = "compas"
version = "0.1.0"
description = "LH Compas 2024 Competition - Time-Series Forecasting for Commercial Vacancy Rates"
authors = ["Woojin Choi <cwwojin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
