name: Lint

on:
    pull_request:
        branches: ["main"]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - run: cd compas
            - name: Run Black Formatter
              uses: psf/black@stable
              with:
                  options: "--check --verbose"
                  src: "./compas"
                  use_pyproject: true
